project:
  type: website
  output-dir: docs

website:
  title: "Data Science With Britney"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/britney-aiken-929373185/
format:
  html:
    theme:
      light: pulse
      dark: vapor



